// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsManagementService.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NewsManagementService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260121180912_IncrementTitleLimit")]
    partial class IncrementTitleLimit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NewsCategoryUserPreferencesReplica", b =>
                {
                    b.Property<int>("SubscribedNewsCategoriesId")
                        .HasColumnType("integer");

                    b.Property<int>("UserPreferencesId")
                        .HasColumnType("integer");

                    b.HasKey("SubscribedNewsCategoriesId", "UserPreferencesId");

                    b.HasIndex("UserPreferencesId");

                    b.ToTable("NewsCategoryUserPreferencesReplica");
                });

            modelBuilder.Entity("NewsManagementService.Models.MacroNewsCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("MacroNewsCategories");
                });

            modelBuilder.Entity("NewsManagementService.Models.NewsCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MacroNewsCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("MacroNewsCategoryId");

                    b.ToTable("NewsCategories");
                });

            modelBuilder.Entity("NewsManagementService.Models.NewsSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NewsCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("NewsCategoryId");

                    b.ToTable("NewsSummaries");
                });

            modelBuilder.Entity("NewsManagementService.Models.UserPreferencesReplica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ShippingHour")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UserPreferencesReplicas");
                });

            modelBuilder.Entity("NewsCategoryUserPreferencesReplica", b =>
                {
                    b.HasOne("NewsManagementService.Models.NewsCategory", null)
                        .WithMany()
                        .HasForeignKey("SubscribedNewsCategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsManagementService.Models.UserPreferencesReplica", null)
                        .WithMany()
                        .HasForeignKey("UserPreferencesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewsManagementService.Models.NewsCategory", b =>
                {
                    b.HasOne("NewsManagementService.Models.MacroNewsCategory", "MacroNewsCategory")
                        .WithMany("NewsCategories")
                        .HasForeignKey("MacroNewsCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MacroNewsCategory");
                });

            modelBuilder.Entity("NewsManagementService.Models.NewsSummary", b =>
                {
                    b.HasOne("NewsManagementService.Models.NewsCategory", "NewsCategory")
                        .WithMany("NewsSummaries")
                        .HasForeignKey("NewsCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsCategory");
                });

            modelBuilder.Entity("NewsManagementService.Models.MacroNewsCategory", b =>
                {
                    b.Navigation("NewsCategories");
                });

            modelBuilder.Entity("NewsManagementService.Models.NewsCategory", b =>
                {
                    b.Navigation("NewsSummaries");
                });
#pragma warning restore 612, 618
        }
    }
}
